server:
  port: 8092
spring:
  config:
    import: "optional:configserver:http://localhost:8071/"
  application:
    name: "accounts"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/accountsdb
    username: root
    password: root1234
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
