build:
  version: "3.0"

loans:
  message: "Welcome to Shamanth Bank loans related local APIs"
  contactDetails:
    name: "Shamanth S - Developer"
    email: "demo1@gmail.com"
  onCallSupport:
    +123456789