spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to Shamanth Bank accounts related QA APIs"
  contactDetails:
    name: "Sahana A - QA Lead"
    email: "demo2@gmail.com"
  onCallSupport:
    +123456789